[bot]
token = "TOKEN"

[database]
models = ["app.db.functions", "aerich.models"]

[settings]
owner_id = 123
throttling_rate = 0.5
drop_pending_updates = false

[sdk]
key = 'key'

[api] # API app settings for Pyrogram Client
# Default values are from Telegram Desktop Client (t.me/durovleaks/108)
# id = 2040 # (Optional) App ID
# hash = "b18441a1ff607e10a989891a5462e627" # (Optional) App hash
# bot_api_url = "https://api.telegram.org" # (Optional) Bot API URL
